---
repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.7.1
    values:
    - "./cert-manager/values.yaml"
    set:
      - name: installCRDs
        value: true
