---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-dns.yaml
  - prom.yaml
  - https://raw.githubusercontent.com/cert-manager/cert-manager/v1.14.4/deploy/crds/crd-certificaterequests.yaml
