apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: monitoring
spec:
  chart:
    spec:
      # renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
      chart: prometheus-operator-crds
      version: '10.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 30m
  releaseName: prometheus-operator-crds
