---
name: "Flux Diff 2"

on:
  pull_request:
    branches: ["master"]
    paths: ["flux/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  diffs:
    name: Compute diffs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_path:
          - clusters/prod
        resource:
          - helmrelease
          - kustomization
    steps:
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2

      - uses: allenporter/flux-local/action/diff@2.1.0
        id: diff
        with:
          live-branch: master
          path: ${{ matrix.cluster_path }}
          resource: ${{ matrix.resource }}

      - name: PR Comments
        uses: mshick/add-pr-comment@v2
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          message-id: ${{ github.event.pull_request.number }}/${{ matrix.cluster_path }}/${{ matrix.resource }}
          message-failure: Unable to post kustomization diff
          message: |
            `````diff
            Diff 2
            ${{ steps.diff.outputs.diff }}
            `````